const ShopTypes ={
    ADD_TO_FAVORITES: "shop/ADD_TO_FAVORITES",
    DECREASE_FAVORITE_ITEM: "shop/DECREASE_FAVORITE_ITEM",
    REMOVE_FAVORITE_ITEM: "shop/REMOVE_FAVORITE_ITEM", 
    DATA: "shop/DATA",
    ADD_BAG_PROPERTY: "shop/ADD_BAG_PROPERTY"
}
export default ShopTypes